
@api = http://localhost:5000/products 

GET {{api}}



###

POST  {{api}}
Content-Type: application/json

{
"name": "tocadiscos",
"description": "Profesional",
"quantity": 9898
}

###

GET {{api}}/3

### Delete


DELETE {{api}}/12

### contador productos


GET {{api}}/count


###

PUT {{api}}/3
Content-Type: application/json

{
"name": "xbox",
"description": "consola video juegos",
"quantity": 50
}