
@api = http://localhost:5000/products 

GET {{api}}



###

POST  {{api}}
Content-Type: application/json

{
"name": "celular",
"description": "Vivo",
"quantity": 100
}

###

GET {{api}}/7

### Delete


DELETE {{api}}/1

### contador productos


GET {{api}}/count


###

PUT {{api}}/7
Content-Type: application/json

{
"name": "xbox",
"description": "consola video juegos",
"quantity": 50
}